# Generated by Django 4.1.5 on 2023-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
